// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_section: dynamic(() => import("./HeroSection")),
  mission_slice: dynamic(() => import("./MissionSlice")),
  solution_slice: dynamic(() => import("./SolutionSlice")),
  team_slice: dynamic(() => import("./TeamSlice")),
  vision_slice: dynamic(() => import("./VisionSlice")),
  whats_next_slice: dynamic(() => import("./WhatsNextSlice")),
};
